### ISSUE TITLE
Preview scrolls to top on edit

### ISSUE THREAD

**Issue by Rulikkk** [mark-hahn/markdown-scroll-sync#11]
Whenever the markdown is edited, preview scrolls to top, thus making this useless.

**Comment by mark-hahn** [comment]
I'll give this high priority.  Can you tell me the versions of OS and
Atom?  Also sending the file it happens on to mark@hahnca.com would be a
big help.

**Comment by Rulikkk** [comment]
Hello and thanks for the reply.

Os: windows 7 sp1
Atom: 0.187.0

Will send the file shortly.

**Comment by mark-hahn** [comment]
I'm sorry for the delay.  I was pretty much gone for two weeks.

I was unable to reproduce the problem, even with your file (thanks for that).  Can you tell me if the problem still happens on the latest version of Atom and this package?

**Comment by bigyuki** [comment]
I'v got the same problem , when i scrolls everything is ok, but  when i was typing, preview auto scrolls to the wrong position.

**Comment by mark-hahn** [comment]
>  preview auto scrolls to the wrong position.

Does it scroll all the way to the top like the original post?

**Comment by bigyuki** [comment]
@mark-hahn 
No, it not scroll to the top.  It scroll to the position as same as if i didn't install this plugin.

**Comment by mark-hahn** [comment]
I'm sorry, but I can't repeat this problem.  If anyone could give me a sequence to repeat this or an animated gif I would really appreciate it.

**Comment by bigyuki** [comment]
@mark-hahn 
![atom-markdown-pre](https://cloud.githubusercontent.com/assets/1812489/7854600/a086e42e-054d-11e5-8961-6c3c2b23e16c.gif)

**Comment by emiola** [comment]
I confirm that the issue is still there, with:

- OS: Mac OS X v10.10.5
- Atom: v1.0.11
- markdown-scroll-sync: v0.4.2

**Comment by crysislinux** [comment]
confirm +1

* OS: Mac OSX El Captain
* Atom: 1.0.19
* markdown-scroll-sync: 0.4.2

**Comment by mark-hahn** [comment]
I've released a new version 2.0.1 that is a total rewrite.  I think it fixes all issues and works much better than before.  Please try it.

**Comment by bigyuki** [comment]
@mark-hahn yes, this issue has been solved, thank you for your effort.

**Comment by Rulikkk** [comment]
:+1: Well done!

**Comment by bigyuki** [comment]
I found that if i enable “markdown-preview” plugin , the issue is also there, so i think it is a “markdown-preview” issue, i use “markdown-preview-plus” instead (enable markdown-preview-plus and disable markdown-preview ), everything is ok.
