### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by TeppoJouttenus** [mark-hahn/markdown-scroll-sync#13]
[Enter steps to reproduce below:]

1. Add an HTML comment into the doc, e.g. 
2. Scroll away so the comment is not visible, then scroll back to see the comment. The error appears

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package, v0.3.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/teppo/.atom/packages/markdown-scroll-sync/lib/main.coffee:108

TypeError: undefined is not a function
    at /Users/teppo/.atom/packages/markdown-scroll-sync/lib/main.coffee:130:35
    at MarkdownScrlSync.module.exports [as roaster] (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/lib/roaster.js:66:14)
    at MarkdownScrlSync.scroll (/Users/teppo/.atom/packages/markdown-scroll-sync/lib/main.coffee:118:19)
    at /Users/teppo/.atom/packages/markdown-scroll-sync/lib/main.coffee:88:19
```

### Commands

```
     -4:23.1 markdown-preview:toggle (atom-text-editor.editor.is-focused)
  2x -0:50.1 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:49.6 core:move-up (atom-text-editor.editor.is-focused)
  5x -0:44.2 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
markdown-scroll-sync, v0.3.2
script, v2.18.0

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
thanks

fixed in 0.3.4

**Comment by TeppoJouttenus** [comment]
Thanks, this is great!

**Comment by steronydh** [comment]
I'm still getting this with 0.3.4.

**Comment by despairblue** [comment]
me too

**Comment by lanceplaine** [comment]
I also have this issue with the `0.4.0` version

```
TypeError: undefined is not a function
  at /Users/kevinlanceplaine/.atom/packages/markdown-scroll-sync/lib/main.coffee:114:21
  at MarkdownScrlSync.module.exports [as roaster] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/roaster/lib/roaster.js:66:14)
  at MarkdownScrlSync.scroll (/Users/kevinlanceplaine/.atom/packages/markdown-scroll-sync/lib/main.coffee:102:6)
  at /Users/kevinlanceplaine/.atom/packages/markdown-scroll-sync/lib/main.coffee:79:10
```

**Comment by kbs0210** [comment]
the same issue with `0.4.0`

> /Users/beomseok.kim/.atom/packages/markdown-scroll-sync/lib/main.coffee:114
Hide Stack Trace
TypeError: undefined is not a function
  at /Users/beomseok.kim/.atom/packages/markdown-scroll-sync/lib/main.coffee:114:21
  at MarkdownScrlSync.module.exports [as roaster] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/roaster/lib/roaster.js:66:14)
  at MarkdownScrlSync.scroll (/Users/beomseok.kim/.atom/packages/markdown-scroll-sync/lib/main.coffee:102:6)
  at /Users/beomseok.kim/.atom/packages/markdown-scroll-sync/lib/main.coffee:79:10

**Comment by banool** [comment]
Same for me on the latest version. Also:
- Whenever you change something or save, you have to scroll the editor a bit to make the preview catch up again.
- The scroll is laggy and often doesn't even work, when it's not crashing.
As others have said before me, this is a bit of a deal breaker for atom. Though I do understand that this is a one man ordeal for making this addon. 
```
TypeError: undefined is not a function
  at /Users/daniel/.atom/packages/markdown-scroll-sync/lib/main.coffee:114:21
  at MarkdownScrlSync.module.exports [as roaster] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/roaster/lib/roaster.js:69:14)
  at MarkdownScrlSync.scroll (/Users/daniel/.atom/packages/markdown-scroll-sync/lib/main.coffee:102:6)
  at /Users/daniel/.atom/packages/markdown-scroll-sync/lib/main.coffee:79:10
````

**Comment by mark-hahn** [comment]
Sorry for the trouble.  I have not put the effort into maintaining this
that it deserves.
