### ISSUE TITLE
looking for scroll-sync for preview-plus/browser-plus

### ISSUE THREAD

**Issue by skandasoft** [mark-hahn/markdown-scroll-sync#15]
Can you add scroll sync work on preview-plus/browser-plus?

![markdown](https://cloud.githubusercontent.com/assets/9875379/7447712/bc91566c-f1cb-11e4-95b0-1d63e4df8465.gif)

**Comment by mark-hahn** [comment]
Do you mean all your previews or just markdown?

I'll take a look soon.  I'm taking a sabbatical for a while from working on projects.

**Comment by skandasoft** [comment]
Yes for the markdown preview. I think that will real useful

**Comment by mark-hahn** [comment]
I've released a new version 2.0.1 that is a total rewrite.  I think it fixes all issues and works much better than before.  Please try it.
