### ISSUE TITLE
Crashes atom constantly plus shaky syncing

### ISSUE THREAD

**Issue by ozra** [mark-hahn/markdown-scroll-sync#16]
It freezes up the editor more and more until crashing it with lots of scrolling issues reported and finally a X Windows error.

The synchronization is also a bit shaky. Perhaps the DOM-node matching algo is a bit over-reaching? I'd be very happy to see an option to simply derive position from cursors relative position in buf, in relation to relative pos in view. A simple percentage based scrolling that is.

I guess that could solve the whole crashing problem, on my machine in any event..

Here's the last few log lines (there's hundreds repeated):

Note that always get this when having the preview open, and never else. So the spell checking thingie might just be a red herring in this case..

```
[28272:0502/232701:INFO:CONSOLE(80)] "markdown-scroll-sync: error in bufferPositionForScreenPosition", source: /home/oscar/.atom/packages/markdown-scroll-sync/lib/main.coffee (80)
[28272:0502/232702:INFO:CONSOLE(80)] "markdown-scroll-sync: error in bufferPositionForScreenPosition", source: /home/oscar/.atom/packages/markdown-scroll-sync/lib/main.coffee (80)
[28272:0502/232702:INFO:CONSOLE(80)] "markdown-scroll-sync: error in bufferPositionForScreenPosition", source: /home/oscar/.atom/packages/markdown-scroll-sync/lib/main.coffee (80)
[28272:0502/232702:INFO:CONSOLE(114)] "Error starting spell check task", source: /opt/atom/resources/app.asar/node_modules/spell-check/lib/spell-check-view.js (114)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 56597 error_code 3 request_code 40 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

```

**Comment by mark-hahn** [comment]
Sorry it took me so long to get to this.  

> So the spell checking thingie might just be a red herring in this case..

Does it happen with the spell-checking package disabled?

The errors you show don't line up with the line number in my code.  And I have a try-catch around that code which makes me think I've already fixed this.  Can you please try this again with the 0.3.4 version I'm about to release?

> I'd be very happy to see an option to simply derive position from cursors relative position in buf, in relation to relative pos in view. 

In many situations the position would be more than a page off.  I don't see how that could be useful.

**Comment by mark-hahn** [comment]
I've released a new version 2.0.1 that is a total rewrite.  I think it fixes all issues and works much better than before.  Please try it.

**Comment by ozra** [comment]
Ssorry for not responding earlier. Later versions of Atom hangs way to often, and has lost me too much work, so I've switched to sublime 3 a few months ago which has yet to crash. I'll check back in later in the hopes it has shaped up. Loved this plugin, so I'm happy to here this! So much smoother than st3 previewing for sure :-)

**Comment by mark-hahn** [comment]
Sorry to hear about your problems (which I take some blame) but happy to read "So much smoother than st3".
