### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by despairblue** [mark-hahn/markdown-scroll-sync#18]
```
TypeError: undefined is not a function
  at /home/despairblue/.atom/packages/markdown-scroll-sync/lib/main.coffee:96:24
  at MarkdownScrlSync.module.exports [as roaster] (/usr/share/atom/resources/app.asar/node_modules/roaster/lib/roaster.js:66:14)
  at MarkdownScrlSync.scroll (/home/despairblue/.atom/packages/markdown-scroll-sync/lib/main.coffee:96:6)
  at /home/despairblue/.atom/packages/markdown-scroll-sync/lib/main.coffee:73:10
```

Also, the tab bar disapears.

## Repro Steps

1. open a markdown file
2. open the markdown preview
3. scroll

## Command History

```
     -0:48.4 pane-container:active-pane-item-changed (atom-pane-container.panes)
     -0:48.4 pane:active-item-changed (atom-pane.pane.active)
     -0:45.6 cursor:moved (atom-text-editor.editor)
     -0:45.6 selection:changed (atom-text-editor.editor)
     -0:23.3 cursor:moved (atom-text-editor.editor)
     -0:23.3 selection:changed (atom-text-editor.editor)
     -0:03.6 pane-container:active-pane-item-changed (atom-pane-container.panes)
     -0:03.6 pane:active-item-changed (atom-pane.pane.active)
     -0:01.2 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 bug-report:open (atom-text-editor.editor.is-focused)
```

## Versions

* **Atom:**       0.205.0
* **Atom-Shell:** 0.22.3
* **OS:**         linux 3.14.43-2-lts
* **Misc**
    * apm  0.168.0
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.10
    * git 2.4.2

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.0.</small>

**Comment by mark-hahn** [comment]
Thanks for the report.

I can't repeat this, and the exception makes no sense.  Can you make sure you are on the latest version of Atom and this package?  Then try to make a repeatable case.  If you can, send the markdown file to mark@hahnca.com.

**Comment by despairblue** [comment]
Ok error is gone, but it still scrolls the tab bar out of view. Should I open another issue for this? 
![screenshot from 2015-06-05 12-13-16](https://cloud.githubusercontent.com/assets/927609/8004005/63d8812e-0b7c-11e5-82cd-0df8e1bda935.png)

The file is [this one](https://github.com/despairblue/scegratoo3/blob/master/README.md) though I have uncommited changes on my laptop.

**Comment by mark-hahn** [comment]
Sure, make an issue.  I don't remember you mentioning this problem.  Br
sure to describe it well.

**Comment by despairblue** [comment]
> Also, the tab bar disapears.

This was meant to describe it, I just assumed it was part of this issue since only the tab bar disappeared, but as you can see in the screenshot I'm able to scroll down way more than that making half of atoms GUI disappear...

I'll make another issue.
