### ISSUE TITLE
Should it work with .litcoffee files?

### ISSUE THREAD

**Issue by michaelforrest** [mark-hahn/markdown-scroll-sync#19]
I will see if I can figure it out (but this will be my first attempt to play with an Atom plugin)

**Comment by mark-hahn** [comment]
> I will see if I can figure it out 

That would be great.  Let me know if I can help.

**Comment by michaelforrest** [comment]
PR right there :) https://github.com/mark-hahn/markdown-scroll-sync/issues/20
