### ISSUE TITLE
Scrolling scrolls atom itself out of view

### ISSUE THREAD

**Issue by despairblue** [mark-hahn/markdown-scroll-sync#21]
![](https://cloud.githubusercontent.com/assets/927609/8004005/63d8812e-0b7c-11e5-82cd-0df8e1bda935.png)

1. open a long markdown file
2. open the preview
3. scroll down very fast

Happens on linux and mac. The first screenshot is from linux with atom 0.206.0, the next one is from mac with atom 0.204.0
![screen shot 2015-06-05 at 20 14 36](https://cloud.githubusercontent.com/assets/927609/8012209/ddc170a2-0bbf-11e5-880b-4d3b2c8e52d8.png)

**Comment by despairblue** [comment]
oh on mac it's actually enough to open the preview.

**Comment by phyllisstein** [comment]
I'm seeing the same behavior on 0.209.0 under Mac OS X, for whatever it's worth; nothing of notice is getting logged to the console, but the tab view seems to just scroll itself away:

![screen_shot](https://cloud.githubusercontent.com/assets/2207980/8150756/1b7b1906-12c4-11e5-9ff3-9e818eb2d5d0.png)

**Comment by nicofrand** [comment]
I have the same issue (which is really annoying since I am using https://atom.io/packages/markdown-preview-opener as well.

**Comment by mark-hahn** [comment]
I apologize for the slow response.  I have been working on a big project.
I'll get back to work on my packages this afternoon.  The pace of Atom
changes have made it challenging to keep up.

**Comment by mark-hahn** [comment]
Is everyone here using a Mac?  I'm on Linux and I can't repeat the problem.  I've loaded up my largest markdown file and scrolled fast.   Any help would be appreciated.

**Comment by despairblue** [comment]
The first screenshot is from a linux box. I'll try again tomorrow with 0.210.0.

**Comment by despairblue** [comment]
I can reliably reproduce it with [this](https://github.com/despairblue/scegratoo3/blob/master/README.md) markdown file.

**Comment by jmanuel1** [comment]
Is anybody working on this?

**Comment by mark-hahn** [comment]
> Is anybody working on this?

I am responsible for this but I have been buried in a non-Atom project.  I don't time-share well.  I will do my best to stop whatever I'm doing this weekend and work on this.

Of course some help would be greatly appreciated since I haven't been able to reproduce the problem in my setup.  Can anyone find use cases where it happens and other use cases that don't show the problem?  I haven't tried @despairblue's file yet.

**Comment by rolfkleef** [comment]
I tried it with [this markdown test file](https://gist.github.com/rolfkleef/c666f7238a11ddeaf40e) on Ubuntu 14.04, Atom 1.0.0, markdown-scroll-sync 0.4.0

It pushes the editor up when scrolling down a bit, and mostly immediately when opening (can't find a reproducible pattern yet).

If I first make a file with 5 "lorems", there is no scroll bar and it works fine. When I then paste everything from the scroll bar at the end of the file, my cursor is at the end of the file and a scrollbar appears, but *the scrollbar is at the top of the file* (bug in Atom? After a second paste, the scrollbar does move in the editor).

A bit of scrolling or dragging the scrollbar makes the editor push up again. It seems to happen when there is more than 10-15% of content off-screen.

I've tried switching themes as well, but without a change in behaviour.

When I click in the preview pane or open another file from the tree pane, Atom returns to its normal state. When I click in the editor again, it shifts up again.

Hope there is something in this that triggers an idea... would be great to have this package work as well :-)

**Comment by rolfkleef** [comment]
This seems to be a similar behaviour in another package: https://github.com/atom/autocomplete-plus/issues/511

They solved it by replacing the call to scrollIntoView() with their own code... https://github.com/atom/autocomplete-plus/commit/4688b67545c3c79a0a39af8d986e735fdd05f974

**Comment by mark-hahn** [comment]
Thanks.  I'll try that .  I knew it couldn't have been my fault.  (grin)

**Comment by dorian-marchal** [comment]
Same issue, here, on Linux.

**Comment by orlade** [comment]
Same issue on Windows. Sorry I can't be much more help atm.

**Comment by mark-hahn** [comment]
I've released a new version 2.0.1 that is a total rewrite.  I think it fixes all issues and works much better than before.  Please try it.
