### ISSUE TITLE
Scroll Sync does not work

### ISSUE THREAD

**Issue by motleytech** [mark-hahn/markdown-scroll-sync#22]
I am on a mac and using the following packages in atom

1. markdown-scroll-syn (mark-hahn)
2. markdown-helpers (catacgc)
3. markdown-lists (brunobord)
4. markdown-pdf (travs)
5. markdown-preview-katex (abejfehr)

After opening the preview pane and scrolling the source file, the preview pane does not scroll automatically.

Is the tool out of date or is it conflicting with Katex preview tool?

**Comment by mark-hahn** [comment]
I released several versions in the past week that fixed bugs and
deprecations.  It should work fine.

So it doesn't scroll at all?  Even on a long file?

One thing you should know is that it doesn't sync sections of a file that
are code or images. It will just hop over them so they appear to not be
scrolling.  Could it be your file has only such sections?

If not please send a sample file to mark@hahnca.com.  Thanks.

**Comment by motleytech** [comment]
Thanks @mark-hahn 

Could it have something to do with *markdown-preview-katex* being a fork of *markdown-preview-plus*?

I just went through the other issues and found a similar one on MPP submitted earlier. (Sorry.... the report issue button in atom landed me on the new issue page, and somehow the page gave me an impression that there were no other issues. My mistake, I didn't search thoroughly.)

I think that its the same case (as MPP) here as there is nothing special in my markdown file. If you still need it, I will be happy to send you the .md file.

**Comment by mark-hahn** [comment]
>  the report issue button in atom landed me on the new issue page
Yes, I posted an issue to atom/atom about that.

What happens if you disable the `markdown-preview-katex` package?

**Comment by motleytech** [comment]
Without the `markdown-preview-katex`, sync seems to work fine.

As you said earlier, it does hiccup on the code or pre sections.

I naively thought that sync would be as simple as reading the scroll position on the source and making the scroll position the same on the preview pane. Apparently, its not that simple.

**Comment by mark-hahn** [comment]
> Apparently, its not that simple

One is a text file and the other is the DOM.  My code works by counting
common elements in the text file that have an exact counterpart in the
DOM.  Then I walk the DOM counting those matching elements.  Unfortunately
there is nothing to match in an image file.

Also, code sections are actually implemented in the preview as complete
read-only text-editors the same as the text-editors found in Atom tabs.
They did this to get free syntax highlighting.  So the editors are a
complex DOM with the code splattered all over.  Also those editors aren't
in the DOM in the order of the original text.  There is absolute
positioning on every line.  I gave up trying to match them.

So I end up with many issues relating to these mismatches.  I wish I could
put up a message when they open a new issue.  Hey, maybe I can.  I'll check.

**Comment by mark-hahn** [comment]
> sync would be as simple as reading the scroll position on the source and
making the scroll position the same on the preview pane

In theory it wouldn't work at all.  One image in the beginning and the
entire rest of the file would be off.  And this type of readme with an
image at the top is very common.

I could possibly go through the DOM getting positions of elements and
subtracting out the image heights.  I could do a similar thing in pre
sections by relating the line count on the left with the text-editor DOM
height on the right.  So I probably could fix this.  I should list this as
an enhancement.

The symptom of hopping doesn't seem bad to me but I understand what is
going on.  It looks broken to everyone else.

**Comment by motleytech** [comment]
Thanks for the great explanation. I definitely understand some of the things that make it complicated.

It has now piqued my interest enough that I will go through the atom package creation tutorials, just for some fun to see what all one can do with this editor.

Thanks for indulging me this long, on an issue that should probably not been filed. ;-)

**Comment by mark-hahn** [comment]
> an issue that should probably not been filed.

No no.  I need all the feedback I can get.

If you decide to write a package feel free to ask for help.  I've tutored
several others by answering questions.  Of course questions on the forum
are also welcome.  I've written 21 packages and several are even useful.

**Comment by motleytech** [comment]
> If you decide to write a package feel free to ask for help.  I've tutored
several others by answering questions.

Dude... did you know that you are awesome. If you didn't let me tell you. You are awesome. Thanks for the offer... I will reach out if I need help.

> several are even useful.
Lol... nice way to put it.

I will now look for your packages specifically.

**Comment by justqb** [comment]
@mark-hahn 
I am sorry.
but this package can't work at all.

OS: win8.1 x64 Chinese version
atom: 0.207
installed package : only "markdown-scroll-sync" 0.4.0

I am a  teacher, use this to show the note to students. sync scroll function is very important.

**Comment by mark-hahn** [comment]
Do you have  large code (pre) sections or images?  It cannot sync inside of
those sections.

Send the file that doesn't work to mark@hahnca.com.

**Comment by justqb** [comment]
i had sent you the file and video to you mail box.

**Comment by justqb** [comment]
hi, mark-hahn.

I don't know what happened . it WORKS.

Thank you! 

I have star this package.
