### ISSUE TITLE
Uncaught Error: Cannot find module 'roaster'

### ISSUE THREAD

**Issue by robsbx** [mark-hahn/markdown-scroll-sync#23]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package, v0.4.0

### Stack Trace

Uncaught Error: Cannot find module 'roaster'

```
At module.js:330

Error: Cannot find module 'roaster'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\michalr1\AppData\Local\atom\app-0.210.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at /C:/Users/michalr1/.atom/packages/markdown-scroll-sync/lib/main.coffee:19:27
    at process._tickCallback (node.js:357:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "autosave",
      "markdown-format",
      "markdown-format"
    ]
  }
}
```

### Installed Packages

```coffee
# User
markdown-scroll-sync, v0.4.0

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
This problem makes no sense.  It says that it can't find the package roaster but roaster is definitely in the npm registry and my package.json.  Can you please try running `apm install` in the `markdown-scroll-sync` folder wherever you keep your packages?  If that doesn't fix it try uninstalling and removing the package.  If that doesn't work please send a copy of the `package.json` file in that folder?

Sorry for your trouble.

**Comment by robsbx** [comment]
When I do `apm install` I get 
```
Installing markdown-scroll-sync to C:\Users\myuser\.atom\packages failed
Request for package information failed: SELF_SIGNED_CERT_IN_CHAIN
```
And there is no `package.json` unfortunately

**Comment by mark-hahn** [comment]
You are having some problem with your apm.  Are other installs working for
you?  Also did you delete the package folder completely?

If you still have problems please try closing all Atom windows, rename your
.~/.atom. folder, run Atom again to create a fresh ~/.atom. folder, and
then install this package.  If this works you can copy the new package
folder to your renamed .atom folder and then rename your real .atom folder
back to ~/.atom.

**Comment by robsbx** [comment]
> You are having some problem with your apm.  Are other installs working for
> you?  Also did you delete the package folder completely?

Yes and yes :)
> If you still have problems please try closing all Atom windows, rename [...]

Same results... Also tried to uninstall and install Atom again.

**Comment by mark-hahn** [comment]
very odd -- i'll do the same here to see if I can repeat it.

**Comment by robsbx** [comment]
Any luck? I really wish I could use the package :)

**Comment by robsbx** [comment]
I think ver 1.0.1 fixed `SELF_SIGNED_CERT_IN_CHAIN` issue. I was able to install `markdown-scroll-sync` without any problems this time.

**Comment by mark-hahn** [comment]
I've released a new version 2.0.1 that is a total rewrite.  I think it fixes all issues and works much better than before.  Please try it.

**Comment by NerdDiffer** [comment]
I had this problem after updating to 2.0.1 on a Linux system

What worked for me is to use the `apm` command in the terminal to uninstall , then reinstall it. When I started up Atom again there were no `roaster` problems. Perhaps atom kept around a cached `package.json` file? I don't know.

**Comment by mark-hahn** [comment]
That's truly weird.  There is no mention of roaster in the repo anymore.  You must be right about caching.  I'll leave this closed.

What do you think of it so far?

**Comment by NerdDiffer** [comment]
It's a huge improvement over the last one, that's for sure. Typically, I'll use `vim-mode` instead of the mouse to scroll around, though trying it with the mouse's scroll wheel seems spot on so far.

Using `vim-mode` takes a little getting used to. For instance, if I want to jump to the bottom of the document with `G` or the top of it with `gg`, the markdown preview is a step behind. But I just have to go to an adjacent line to get the preview pane to "catch up".

Overall, it's quite good. Thanks!

**Comment by mark-hahn** [comment]
>  if I want to jump to the bottom of the document with G or the top of it
with gg, the markdown preview is a step behind

Hmm.  I use an event from Atom that says the cursor-moved.  Either it is
flakey or I have a bug that uses an old event.  Can you create a new
issue?  I like for the issues to record properly who reported them.

**Comment by baelter** [comment]
[Enter steps to reproduce below:]

Got error while upgrading to markdown-scroll-sync 2.0.3

**Atom Version**: 1.2.3
**System**: "Manjaro Linux"
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package, v2.0.3


### Stack Trace

Uncaught Error: Cannot find module 'roaster'

```
At module.js:338

Error: Cannot find module 'roaster'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/anders/.atom/packages/markdown-scroll-sync/lib/main.coffee:10:7
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
     -8:34.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:32.1.0 atom-beautify:beautify-editor (atom-text-editor.editor)
     -8:30.7.0 core:save (atom-text-editor.editor.is-focused)
  4x -8:01.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:51 core:cut (atom-text-editor.editor.is-focused)
     -7:49.4.0 core:paste (atom-text-editor.editor.is-focused)
 17x -7:48.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -7:46.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -7:45.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:44.5.0 core:save (atom-text-editor.editor.is-focused)
  3x -7:42.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:30.9.0 core:save (atom-text-editor.editor.is-focused)
     -7:26.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:08.0 core:save (atom-text-editor.editor.is-focused)
     -0:40.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:40.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/home/anders/Projects",
    "autoHideMenuBar": true,
    "ignoredNames": [
      ".git",
      "node_modules"
    ],
    "disabledPackages": [
      "json-schema",
      "autocomplete-ctags",
      "atom-ternjs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-beautify, v0.28.19
autoclose-html, v0.19.0
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
autocomplete-python, v0.10.4
autocomplete-sass, v0.1.0
color-picker, v2.0.13
compare-files, v0.6.2
css-snippets, v0.9.0
custom-title, v1.0.1
docblockr, v0.7.3
editorconfig, v1.2.2
external-open, v0.6.1
file-icons, v1.6.12
flex-tool-bar, v0.6.0
git-log, v0.4.1
go-plus, v3.5.2
highlight-selected, v0.11.1
language-diff, v0.4.0
language-groovy, v0.4.0
language-nginx, v0.6.1
language-qml, v1.0.0
language-rspec, v0.3.0
language-svg, v0.9.0
linter, v1.11.2
linter-clang, v3.3.0
linter-coffeelint, v1.1.2
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-javac, v1.3.0
linter-jscs, v3.2.0
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-pylint, v1.0.5
linter-ruby, v1.2.0
linter-scss-lint, v2.4.0
linter-shellcheck, v1.0.2
linter-xmllint, v1.1.0
local-history, v3.2.3
markdown-scroll-sync, v2.0.3
minimap, v4.16.1
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
pigments, v0.19.0
pretty-json, v0.4.1
project-manager, v2.6.5
regex-railroad-diagram, v0.10.4
rspec-snippets, v0.4.0
simple-drag-drop-text, v0.3.0
svg-preview, v0.6.1
symbol-gen, v1.0.0
symbols-tree-view, v0.10.1
sync-settings, v0.6.0
synced-sidebar, v0.4.3
tabs-to-spaces, v1.0.1
tool-bar, v0.1.9
trailing-spaces, v0.3.2
zentabs, v0.8.6

# Dev
symbol-gen, v1.0.0
```

**Comment by navjotjsingh** [comment]
Getting the same error as @baelter  with v2.0.3 on Windows 10.

**Comment by mark-hahn** [comment]
Until I figure out this weirdness you can go to the project folder and do
`npm install roaster`.
