### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by Syst** [mark-hahn/markdown-scroll-sync#29]
Comment : 
I'm totally new to signaling errors on git but I just tried to install your package in atom through the apm install process and it doesn't work. I was on the 1.0.7 when I installed markdown-scroll-sync, on Linux Mint the error told me it could be related to not being in 1.0.11 I did the update but it still doesn't work (the error part related to 1.0.11 isn't here anymore), I tried a few basic tests / uninstall / reinstall but nothing worked.

I'm apologizing in advance if it's not the good way to signal the problem or else and thanks for the work in the package, I really hope I make it work, this feature is really missing in atom !

[Generated bug issue from atom]
**Atom Version**: 1.0.11
**System**: Linux Mint
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package, v0.4.2

### Stack Trace

Uncaught TypeError: object is not a function

```
At /home/user/.atom/packages/markdown-scroll-sync/lib/main.coffee:23

TypeError: object is not a function
    at /home/user/.atom/packages/markdown-scroll-sync/lib/main.coffee:23:24
    at process._tickCallback (node.js:357:13)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
markdown-scroll-sync, v0.4.2

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
I've released a new version 2.0.1 that is a total rewrite.  I think it fixes all issues and works much better than before.  Please try it.

**Comment by Syst** [comment]
Thanks for this work ! I did the update and got the same issue than here :  https://github.com/mark-hahn/markdown-scroll-sync/issues/23 but uninstalling it and reinstalling with apm as the other person did the trick ! It looks like it works perfectly now ! Thanks a lot :-)

**Comment by mark-hahn** [comment]
I wish I could fix the roaster problem.  Some people may not know to run
apm.

Can anyone figure out why this is happening?

Idea: I'll put roaster in the dependencies even though I don't use it.
That should work.
