### ISSUE TITLE
Does not sync at all

### ISSUE THREAD

**Issue by rugk** [mark-hahn/markdown-scroll-sync#30]
I tested it with Atoms license file and it does not do anything at all:
![markdownnosync](https://cloud.githubusercontent.com/assets/11966684/9889113/31a33f78-5bf9-11e5-9ccb-9d7d1a4bdf8e.gif)

Atom 1.0.11
Windows 7

**Comment by kazuki-isogai** [comment]
same issue occured on same os/atom version

**Comment by firefoxForUser** [comment]
Package is working for few first lines of .md document, then it isn't working.

**Comment by rugk** [comment]
It seems there won't be much development of this in the future: https://github.com/mark-hahn/markdown-scroll-sync/issues/33

**Comment by mark-hahn** [comment]
I've released a new version 2.0.1 that is a total rewrite.  I think it fixes all issues and works much better than before.  Please try it.

**Comment by rugk** [comment]
Nice it syncs scrolling now.
