### ISSUE TITLE
Request to have this package removed

### ISSUE THREAD

**Issue by banool** [mark-hahn/markdown-scroll-sync#33]
As has been said by the author of this tweak himself, this package is deprecated and he is no longer supporting it. Considering that this package, at least in my experience (tried on multiple machines and over many version of atom), works tentatively at best, with a jerky and inaccurate sync, and at the worst just doesn't work at all or repeatedly crashes, I am formally requesting that this package be taken down or marked as deprecated so that development can recommence by someone else.

The lack of scroll sync and decent markdown editing, like you have Macdown for example, is a real killer for me being able to tolerate atom and I'm sure I'm not alone. This is especially concerning considering that github has made such a push to have markdown become a standard, and is quite incredible that it has even had to fall to individuals such as Mark to implement features such as this themselves instead of just being created by the core dev team.

Any input on this suggestion would be welcome because I want to get the ball rolling again on making atom a great editor.

**Comment by mark-hahn** [comment]
I'll put a notice that I am not supporting it.  Calling it deprecated would be incorrect since there is nothing replacing it.  I'm not removing it because that would stop others from picking up support.

As to whether it should be in core, you should discuss that on atom/atom, not here.

**Comment by banool** [comment]
Yeah my mistake, a poor choice of words. Thanks for the quick response, don't get me wrong I definitely appreciate what you've done so far. I'll take the issue to atom/atom, thanks.

**Comment by mark-hahn** [comment]
You should be happy to know that I've release a new version 2.0.1 that is a total rewrite.  I think it fixes all issues and works much better than before.  Please try it for me.
