### ISSUE TITLE
Slows down with large files: Configurable delay?

### ISSUE THREAD

**Issue by rugk** [mark-hahn/markdown-scroll-sync#34]
When using large files this can slow down very much. E.g. try the license file of Atom.
![syncissues](https://cloud.githubusercontent.com/assets/11966684/11318361/885f39cc-904f-11e5-9b35-7ac3ccb3aa16.gif)

So what I suggest would be adding a (configurable) delay so that it is not instantly synced to reduce system load.

**Comment by mark-hahn** [comment]
Do you mean that the source is also slow, or just the syncing?

**Comment by rugk** [comment]
The source too. It just seems to hang often.

**Comment by mark-hahn** [comment]
I can work on fixing the slowdown.  I never tried large files, which now
that I think about it was really stupid of me.

**Comment by mark-hahn** [comment]
Jeez, that file is 10,000 lines.  I don't think it is representative but if I can make that fast then everything should be.  Mapping the source to the preview takes 1.5 seconds.

Version 2.0.2 does not perform the slow mapping process when just scrolling or moving the cursor now.  So just reading the file is fast after a delay during loading.  However, it still has the slowdown when editing.  Typing in new text is intolerable on that file.

I'm investigating how to let the rest of atom run while the mapping happens.  It needs to be done in chunks releasing the event loop often.  This may have a new problem of the sync being inaccurate but that innacuracy would only last a second or two, on this sized file, and may not be a problem.

**Comment by mark-hahn** [comment]
2.0.2 introduced an accuracy bug.  Until I find out what's going on I've released 2.0.3 which just removes the changes in 2.0.2.

I'm giving this a bit of a low priority for two reasons.

1) Editing in the giant file without this package is also unusable.  And loading the readme to begin with is really slow.  I thought this package was causing all the problem.

2) When I chopped the file down from 10,000 lines to 2,000 there was no speed problem any more.  Anyone crazy enough to make a 10,000 line markdown file shouldn't bring up the preview.

I am going to work on this though.  It never hurts to have better performance than needed.  I'm keeping it open.

BTW, I never thanked you before for doing this experiment and bringing it to my attention.  Thanks...

**Comment by rugk** [comment]
> 1) Editing in the giant file without this package is also unusable. And loading the readme to begin with is really slow. I thought this package was causing all the problem.

No, in my test loading the Readme took about 5 seconds, which is indeed not fast (and I have pretty much Atom extensions installed), but it feels okay. Because obviously you can understand that such a file needs to load a few seconds more and it is only one time.
The delay when scrolling happens every time you scroll so it - subjectively - feels much more annoying.

![ReadmeSlowdown](https://i.imgur.com/lN43yHP.gif)
(big file, [video version](https://imgur.com/lN43yHP))

> Anyone crazy enough to make a 10,000 line markdown file shouldn't bring up the preview.

Quite true. But if you have `markdown-preview-opener` installed... :wink: 

No problem in giving this low priority. (you can also tag it like this :smile:)
And...
> BTW, I never thanked you before for doing this experiment and bringing it to my attention. Thanks...

Doing this was not really a big deal.

**Comment by mark-hahn** [comment]
I haven't had time to work on this as it is not a big problem, IMHO.  I'm marking it as wontfix.
