### ISSUE TITLE
Not working with GFM disabled

### ISSUE THREAD

**Issue by claudio-silva** [mark-hahn/markdown-scroll-sync#37]
Sorry, but it is not working for me. No scroll at all. Latest version of Atom. I disabled all other markdown-related plugins except for the core markdown-preview.

**Comment by claudio-silva** [comment]
I found the problem: I had to enable the `language-gfm` core plugin, otherwise it won't work.
> Note for reproducing the bug: enabling the plugin `language-gfm` solves the problem immediately, but disabling it requires a restart of the IDE to make the problem manifest itself.

If you could make your plugin independent of the `language-gfm` plugin it would cause less frustration for other users that may stumble into this. If you thing it's not worth the trouble, I suggest that, at least, you could warn the user about this requirement on the Readme.

**Comment by mark-hahn** [comment]
Why did you have it disabled?  Aren't core packages always supposed to be
enabled?

**Comment by claudio-silva** [comment]
Well, one might not want the Github Markup Format functionality, or it may interfere with some plugin.

Also, sometimes you may need to disable a core package in order to replace it with another package (just one example: the Markdown Preview).

**Comment by mark-hahn** [comment]
So language-gfm is for Github Markdown Format?  What format were you using?
 markdown-scroll-sync has only been tested with the normal gihub markdown
preview.

**Comment by claudio-silva** [comment]
Note: I disabled the package because I disabled all packages related to Markdown in order to find out which package was causing problems with the Markdown Preview (a problem that is not related to you, in any way). That's when your package stopped working, even after being re-enabled. Then, I just forgot to reenable `language-gfm` because it doesn't show up when one searches for 'markdown'.

Look, I didn't mean to bother you with this and I know you are a busy person. It's just that I spent a lot of time trying to make your package work again, and I was about to give up when I found out the culprit.
So I decided to let you know about this, in the hope that, at least, you could put a warning about it on the Readme, so that we could spare other users from, eventually (yes, I know it may be rare, but it happens!), going trough the same that I did.

Best regards, and thank you for this excelent package.

**Comment by mark-hahn** [comment]
>  you could put a warning about it on the Readme,

Since you understand the problem can you put in a pull request with a
subtle warning?  It would really help.

I'm sorry I haven't thanked you for the work you've done.  I've been buried
in a ton of work.

**Comment by OJFord** [comment]
> markdown-scroll-sync has only been tested with the normal gihub markdown preview.

Note that Github Flavoured Markdown (GFM) != 'normal markdown'.

GFM adds tables and syntax highlighting for code to the standard markdown core.

I don't see that there's any reason for markdown edit/preview synchronisation to depend on the formatting dialect? If this reliance exists, I'd suggest it's definitely a bug.

**Comment by mark-hahn** [comment]
> I don't see that there's any reason for markdown edit/preview
synchronisation to depend on the formatting dialect?

I check to make sure it is an md doc.  It should work otherwise.  What
grammar do your documents show?

**Comment by OJFord** [comment]
> I check to make sure it is an md doc.

Ah, I see.

Well, without GFM there is no syntax-highlighting to be done; no `language-` package. I see your check for whether the name is one of [GFM, CS], but I'm not sure how to check what it is with `language-gfm` disabled? Could you just check for a `.md` file extension?

Also, there are currently 3  similarly titled issues.. Can I suggest re-titling this one along the lines of "not working with GFM disabled"? :)

**Comment by mark-hahn** [comment]
>Could you just check for a .md file extension?

I might be doing that.  I don't remember.  I'm buried right now and it
could speed things up if you looked at the code.  You don't need to change
anything and do a PR.  Just saving my time would help.

**Comment by OJFord** [comment]
I did take a look, I'm afraid I couldn't give you a PR if I tried though - still new to Atom and CoffeeScript.

> Could you just check for a .md file extension?
> I might be doing that

Right now you're checking the name of the grammar in the editor (as auto-detected, or whatever)
https://github.com/mark-hahn/markdown-scroll-sync/blob/master/lib/main.coffee#L26-L29
```coffee
isMarkdown = (editor)->
        for name in ["GitHub Markdown", "CoffeeScript (Literate)"]
          return true if editor.getGrammar().name is name
        return false
```

I suppose my suggestion would be to replace `return false` with `return fileExtensionIsMD`. I might have a crack at it later, but as I say I'm new to it all, and really don't know what that might look like.

**Comment by funkinezz** [comment]
Just wanted to thank Mr. Hahn and contributors for identifying the extension dependency. I had no qualms with mass-renaming my .txt files to .md (thus having atom identify the syntax as GFM), and that solved it for now.
Thank you so much for sharing this, not having Marked 2 on my Windows-PC was killing me, this is a solid replacement.

**Comment by OJFord** [comment]
@funkinezz If you'd rather not rename to .md, you can set the format manually, overriding auto detection - or indeed set markdown to be the language used for .txts

**Comment by mark-hahn** [comment]
You can also hack my code to remove the check.
