### ISSUE TITLE
HTMLElement.shadowRoot is deprecated.

### ISSUE THREAD

**Issue by andykimchris** [mark-hahn/markdown-scroll-sync#433]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
HTMLElement.shadowRoot (/usr/share/atom/resources/app.asar/src/text-editor-element.js:13:10)
MarkdownScrlSync.getVisTopHgtBot (/home/andrew/.atom/packages/markdown-scroll-sync/lib/utils.coffee:20:33)
MarkdownScrlSync.setMap (/home/andrew/.atom/packages/markdown-scroll-sync/lib/map.coffee:25:14)
MarkdownScrlSync.startTracking (/home/andrew/.atom/packages/markdown-scroll-sync/lib/main.coffee:75:12)
<unknown> (/home/andrew/.atom/packages/markdown-scroll-sync/lib/main.coffee:58:23)
Function.module.exports.Emitter.simpleDispatch (<embedded>:66262:20)
```

**Comment by andykimchris** [comment]
I'm not sure what this means.Some help please?

**Comment by Caseraw** [comment]
I have this same issue.

Maybe this can help you?
http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html
https://flight-manual.atom.io/shadow-dom/sections/removing-shadow-dom-styles/

**Comment by andykimchris** [comment]
Awesome thanks.
