### ISSUE TITLE
Throwing exception when I have new unsaved files

### ISSUE THREAD

**Issue by littlecharva** [mark-hahn/markdown-scroll-sync#46]
Hi,

When I have any new unsaved files (so they don't have a path), the package throws an error at times.  You're splitting the response to editor.getPath() without checking for an undefined return value on line 29 of main.coffee.

Apologies, I would have submitted a pull request, but I've literally just installed Atom for the first time, and I just signed up for Github to post this message.  I'll become au fait with it it all and submit pull requests in future.

Anthony

**Comment by mark-hahn** [comment]
Thanks.  Fixed in 2.1.2.
