### ISSUE TITLE
Problems syncing with code sections

### ISSUE THREAD

**Issue by fredlebel** [mark-hahn/markdown-scroll-sync#5]
The scroll goes out of sync when it encounters Github flavoured code snippets.

Create a markdown file with the following piece duplicated enough to require scrolling.

    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
    
    ``` javascript
    var foo = function() {
        bar1();
        bar2();
        bar3();
    }
    ```

**Comment by mark-hahn** [comment]
Thanks for the report.

Have you tried this with the version I released a few hours ago?  0.2.0?  I
specifically changed how it deals with code.  If you have tried it let me
know and I'll test your code.

**Comment by fredlebel** [comment]
With 0.2.0 I get an exception.

    Uncaught ReferenceError: fs is not defined
    /home/fred/.atom/packages/markdown-scroll-sync/lib/main.coffee:80
    ReferenceError: fs is not defined
      at /home/fred/.atom/packages/markdown-scroll-sync/lib/main.coffee:80:7
      at MarkdownScrlSync.module.exports [as roaster] (/nix/store/r02a44p1z5aps6flmb6rfwmskma29d2j-atom-0.171.0/share/atom/resources/app/node_modules/roaster/lib/roaster.js:66:14)
      at MarkdownScrlSync.scroll (/home/fred/.atom/packages/markdown-scroll-sync/lib/main.coffee:79:6)
      at /home/fred/.atom/packages/markdown-scroll-sync/lib/main.coffee:59:10

**Comment by mark-hahn** [comment]
Oops.  I left some breaking debug statements in.  I've got to add some spec testing.  This breakage was fixed in 0.2.1

**Comment by fredlebel** [comment]
With 0.2.1 it just stops scrolling entirely when it hit the code block in the markdown I posted above.

**Comment by mark-hahn** [comment]
I can't repeat this.  Did you reload Atom after upgrading to 2.0.1?  Can
you send me the exact ms file that causes the exception?

**Comment by fredlebel** [comment]
It's really just that blob I pasted earlier repeated a bunch of times.  I am running an older version of Atom 1.7.1.  I'll try to upgrade and retest.

**Comment by fredlebel** [comment]
Yup, works much better in Atom 0.187.0.

**Comment by mark-hahn** [comment]
Thanks again.
