### ISSUE TITLE
Issue with end of file

### ISSUE THREAD

**Issue by jeromeetienne** [mark-hahn/markdown-scroll-sync#6]
thanks for your extension!

i think there is a small issue with end of file. see the attached screenshot. the top of the markdown preview is higher than the top of the .md text edit window.

So the end of the .md text isnt shown in the preview, even if my cursor is at the very end of the .md

![screen shot 2015-03-11 at 10 39 38](https://cloud.githubusercontent.com/assets/252962/6593698/2da66eac-c7db-11e4-93d7-e4b93be5a0a0.png)

**Comment by jeromeetienne** [comment]
here is a link to the file snapshotted above. it may helps reproduce the issue

https://github.com/jeromeetienne/jsdoced.js/blob/master/README.md

**Comment by mark-hahn** [comment]
Thanks very much for the report.

FYI: Currently I'm syncing top to top, which is causing this problem and has to be fixed.  Unfortunately the scroll-into-view method for DOM elements can only sync to top or bottom.  I'll try switching from syncing tops to syncing bottoms half-way through the file but there will be a jump at that point no matter how small.  I'll try that but I may have to work a bit harder.

**Comment by mark-hahn** [comment]
Just a fun factoid: I just realized that it is impossible to fix this in general.  If the markdown source is less than a screen tall and the preview is more that a screen tall, then there is no way to scroll the preview to the bottom because you can't scroll the source.

**Comment by mark-hahn** [comment]
When I loaded your file I couldn't repeat your problem.  I couldn't on any file I had.

Anyway, I added code that forces preview to scroll to the bottom when the source is at the bottom.  Let me know if it doesn't fix your problem.

Fixed in 0.3.0

**Comment by jeromeetienne** [comment]
Thanks for your fast reaction. About the fixability and the fact the markdown preview may be larger than the original .md text...

What about the handling this by the cursor position ? like 'the current cursor position MUST be visible'  ?

**Comment by jeromeetienne** [comment]
here is another case with the top of the file, this time. the issue was the same with the previous version of the package.

here is the [file](https://github.com/jeromeetienne/demo.videovr360/blob/master/ar-vr-report/REPORT.md). note that my cursor in on top of the file and that the tile isnt shown in the preview

![screen shot 2015-03-12 at 13 52 08](https://cloud.githubusercontent.com/assets/252962/6618111/4452dc40-c8c0-11e4-867c-03f57c7f9015.png)

**Comment by mark-hahn** [comment]
>  like 'the current cursor position MUST be visible' ?

I can argue that it is just as easy to use the scroll bar in the preview.  It is something everyone already knows about so it wouldn't be a secret behavior.

> here is another case with the top of the file

Can you do me a favor and post this as a new issue?

BTW, Do you think the last fix worked?

**Comment by jeromeetienne** [comment]
> like 'the current cursor position MUST be visible' ?

About that, here im just suggesting. If you dont feel it is important, this is cool. i know opensource takes time and i do appreciate your work. 

if i feel it bother me, i would do a pullrequest or a fork :)

> BTW, Do you think the last fix worked?

Yep it did worked thanks. here is a screenshot below of the current version

![screen shot 2015-03-12 at 19 55 37](https://cloud.githubusercontent.com/assets/252962/6625690/dc2e252a-c8f1-11e4-8fdf-e1d2e07aaad1.png)

**Comment by mark-hahn** [comment]
> like 'the current cursor position MUST be visible' ?

When I first saw this suggestion I was thinking that it was meant as a way
for the user to control the preview scroll by clicking in the source.

But now I realize it would work naturally that if you were typing at the
bottom or top the preview would scroll.

Can you make this an issue?

**Comment by jeromeetienne** [comment]
is this still needed ? it seems to work without any glitches here. on my files at least.

**Comment by mark-hahn** [comment]
This issue is fixed.  I'll add a new one for your idea of matching the cursor position.
