### ISSUE TITLE
Issue with begining of the file

### ISSUE THREAD

**Issue by jeromeetienne** [mark-hahn/markdown-scroll-sync#8]
Here is a bad case with the top of the file.

Here is the [file](https://github.com/jeromeetienne/demo.videovr360/blob/master/ar-vr-report/REPORT.md). note that my cursor in on top of the file and that the tile isnt shown in the preview

![screen shot 2015-03-12 at 13 52 10](https://cloud.githubusercontent.com/assets/252962/6618114/4e0a9ffc-c8c0-11e4-83bf-69b04057e199.png)

**Comment by mark-hahn** [comment]
Thanks very much for the report.

Fixed in 0.3.2

**Comment by jeromeetienne** [comment]
excelent! thanks
